### PR TITLE
[TOR] Implement SASO Side User Interface

### PR DESCRIPTION
**Pull request by KiyoScript**
Resolves: https://github.com/ShadowFiend23/TOR/issues/33

Only these two page we need to create a UI since the others are already exists. 

image
image

Please Review @akym-03  @micah221b  @rosfloresdelan

### CODE REVIEW

**Comment by micah221b** [comment]
@KiyoScript Palihog ilisan ang interview score into examination score. TY

**Comment by micah221b** [comment]
413243275_1713078512522800_7847608499890072250_n

**Comment by KiyoScript** [comment]
Noted

**Comment by KiyoScript** [comment]
@micah221b  Already Done :+1:  check [here](https://github.com/ShadowFiend23/TOR/commit/722aa4ccc843ef1b18d8b46b3211894b110180d1)

**Pull request merged**
